apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
spec:
  template:   
    spec:
      containers:
        - name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ""
              valueFrom:
                secretKeyRef:
                  name: dbpassword
                  key: password