apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
commonLabels:
  env: prod
namePrefix: prod-
bases:
  - ../base
secretGenerator:
  - name: dbpassword
    envs:
      - .prod.env
resources:
  - namespace.yaml
patchesStrategicMerge:
  - mysql-deployment-patch.yaml
  - wordpress-deployment-patch.yaml
