apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    spec:      
      containers:
        - name: wordpress
          env:     
            - name: WORDPRESS_DB_HOST
              value: prod-wordpress-mysql      
            - name: WORDPRESS_DB_PASSWORD
              value: ""
              valueFrom: 
                secretKeyRef:
                  name: dbpassword
                  key: password
